#ifndef KERN_SYSCALLNO_H
#define KERN_SYSCALLNO_H

#ifndef __ASSEMBLER__
#define _SYSCALLNO(x) x,
enum syscallno {
#endif

    _SYSCALLNO(SYS_SPAWN)
    _SYSCALLNO(SYS_GETTID)
    _SYSCALLNO(SYS_GETPTID)
    _SYSCALLNO(SYS_YIELD)
    _SYSCALLNO(SYS_EXIT)
    _SYSCALLNO(SYS_SEND)
    _SYSCALLNO(SYS_RECV)
    _SYSCALLNO(SYS_WAITEVENT)
    _SYSCALLNO(SYS_TASKSTAT)
    _SYSCALLNO(SYS_SUSPEND)
    _SYSCALLNO(SYS_CHANNEL)
    _SYSCALLNO(SYS_CLOSE)
    _SYSCALLNO(SYS_CHANFLAGS)
    _SYSCALLNO(SYS_DUP)

#ifndef __ASSEMBLER__
};
#endif

#endif /* KERN_SYSCALLNO_H */
