#!/bin/bash -e

utils=$(dirname $0)
redo-ifchange $0 $utils/common.sh
source $utils/common.sh

archive=$1; shift

for arg; do
  DEPS=(${DEPS[@]} $(dirname $arg)/obj/$(basename $arg))
done

DEPS=(${DEPS[@]/.c/.o})
DEPS=(${DEPS[@]/.S/.o})

for dep in ${DEPS[@]}; do
  mkdir -p $(dirname $dep)
done

redo-ifchange ${DEPS[@]}

${XAR} crs $archive ${DEPS[@]}
