#!/bin/bash -e

utils=$(dirname $0)
redo-ifchange $0 $utils/common.sh
source $utils/common.sh

out=$1; in=$2; deps=$out.deps.tmp

asm=${in/obj\//}.S
if test ! -e "$asm"; then
  if test -e "$useclang" -a ! -e "$in.s.do" -a -n "$emit_llvm"; then
    asm=$in.ll
  else
    asm=$in.s
  fi
fi

redo-ifchange $asm

case $asm in
  *.ll)
    ${LAS} -o $out $asm
    ;;
  *.s)
    ${XAS} -c -o $out $asm
    ;;
  *.S)
    ${XAS} -c ${CFLAGS} -MD -MF $deps -o $out $asm
    DEPS=$(sed -e "s?^$out: ??" -e "N;" -e 's/\\//g' < $deps)
    redo-ifchange $DEPS
    ;;
esac
