#!/bin/bash -e

utils=$(dirname $0)
redo-ifchange $0 $utils/common.sh
source $utils/common.sh

out=$1; shift

redo-ifchange $@ $utils/../omap3.ld

${XLD} ${CFLAGS} ${LDFLAGS} -T $utils/../omap3.ld -o $out $@ $LDLIBS
