#ifndef KERN_EVENT_H
#define KERN_EVENT_H

#define NEVENTS 5

#define EVENT_CONSOLE_TRANSMIT 0
#define EVENT_CONSOLE_RECEIVE 1
#define EVENT_ETH_TRANSMIT 2
#define EVENT_ETH_RECEIVE 3
#define EVENT_CLOCK_TICK 4

#endif /* KERN_EVENT_H */
